# Generated by Django 3.2.3 on 2021-05-15 13:42

from django.conf import settings
from django.db import migrations


def create_objects(apps, schema_editor):
    ExpenseCategory = apps.get_model('spendmoney', 'ExpenseCategory')

    default_categories = ['Еда', 'Путешествия', 'Одежда', 'Здоровье', 'Развлечения', 'Прочее']
    batch = [
        ExpenseCategory(name=nm) for nm in default_categories
    ]

    ExpenseCategory.objects.bulk_create(batch)


class Migration(migrations.Migration):
    dependencies = [
        ('spendmoney', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
